project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: solarized
    highlight-style: monokai
    background-transition: slide
    slide-number: true
    incremental: true
    center: false
    navigation-mode: linear
    code-line-numbers: true
    multiplex: true
    code-copy: true
    css: styles.css
    title-slide-attributes:
      data-background-color: "#1a1a2e"
      data-background-image: "assets/Splash_page.png"
      data-background-opacity: "0.7"
